name: hello_world
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1


environment:
  sdk: ^3.11.0-169.0.dev

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^6.0.0

  ffigen: ^20.1.1